name: warranty_watch
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  autoequal: ^0.7.1
  bloc: ^8.1.2
  camera: ^0.10.5+2
  cloud_firestore: ^4.8.2
  copy_with_extension: ^5.0.2
  cupertino_icons: ^1.0.5
  dio: ^5.3.4
  dots_indicator: ^3.0.0
  equatable: ^2.0.5
  expandable: ^5.0.1
  file_picker: ^6.1.1
  firebase_analytics: ^10.4.3
  firebase_app_check: ^0.2.0
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  firefuel: ^0.4.0+1
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.0
  flutter_cupertino_datetime_picker: ^3.0.0
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  go_router: ^12.1.1
  go_router_paths: ^0.2.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.4
  home_widget: ^0.3.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.0
  intl: ^0.18.0
  jiffy: ^6.2.1
  json_annotation: ^4.8.1
  marquee: ^2.2.3
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler: ^11.0.1
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.11
  uuid: ^4.1.0

dev_dependencies:
  autoequal_gen: ^0.7.1
  bloc_test: ^9.1.2
  build_runner: ^2.1.7
  copy_with_extension_gen: ^5.0.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
scripts: derry.yaml

flutter:
  fonts:
    - family: SignInOptions
      fonts:
        - asset: assets/SignInOptions.ttf

  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  # debug token: 6843C3D7-CAA9-475F-AF65-23940B38DC69
